spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_appraiser
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true